providers:
  - name: provider1
    url: https://provider1-dev.com/v1/api/account/validate
  - name: provider2
    url: https://provider2-dev.com/v2/api/account/validate
  - name: provider3
    url: https://provider3-dev.com/v2/api/account/validate
  - name: provider4
    url: https://provider4-dev.com/v2/api/account/validate
  - name: provider5
    url: https://provider5-dev.com/v2/api/account/validate